gui:
  authorColors:
    '*': '#b4befe'
  border: rounded
  theme:
    activeBorderColor:
      - '#89dceb'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#89dceb'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
  showFileTree: true # for rendering changes files in a tree format
  showListFooter: false # for seeing the '5 of 20' message in list panels
  showRandomTip: false
  showBottomLine: false # for hiding the bottom information line (unless it has important information to tell you)
  showCommandLog: false
  showIcons: false # deprecated: use nerdFontsVersion instead
  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
os:
  editCommand: 'nvim'
confirmOnQuit: true
disableStartupPopups: true
notARepository: 'skip' # one of: 'prompt' | 'create' | 'skip'
